### ISSUE TITLE
code for the anticipation task

### ISSUE THREAD

**Issue by scoleri-mr** [fpv-iplab/EASG#3]
Hello!
I can't seem to find in your repo the code related to the anticipation task. Would you consider uploading it?

**Comment by RodinIvan** [comment]
Hi! We've uploaded the notebook with the code we used for the OpenAI API calls. Please note:
1) this code is based on the file pre-processed for downstream tasks (we uploaded it as well);
2) the model `text-davinci-003` is deprecated, so if you plan to use OpenAI API, consider changing it to a newer version.
